//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Book_Sale_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public string Release_Date { get; set; }
        public string Genre { get; set; }
        public string Cover { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Isbn { get; set; }
        public Nullable<int> Piece { get; set; }
        public int Price { get; set; }
        public string Image_Src { get; set; }
    }
}
